services:
  PA:
    image: 'mysql:8.0' 
    environment:
      - 'MYSQL_DATABASE=locadora'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
